publishers:
  tower/head_yaw_position_controller/state: ['/gazebo',]
  nodelet_manager/bond: ['/nodelet_manager','/yocs_cmd_vel_mux',]
  tower_top_kinect/rgb/camera_info: ['/gazebo',]
  tower_top_kinect/depth/image_raw: ['/gazebo',]
  tf: ['/robot_state_publisher','/gazebo','/mono_odometer',]
  tower_top_kinect/depth/points: ['/gazebo',]
  yocs_cmd_vel_mux/parameter_updates: ['/nodelet_manager',]
  tower/head_pitch_position_controller/state: ['/gazebo',]
  mux_vel_raw/cmd_vel: ['/virtual_effector_base_controller',]
  tower/head_pitch_position_controller/pid/parameter_descriptions: ['/gazebo',]
  head_camera_rgb/parameter_updates: ['/gazebo',]
  bottom_kinect/parameter_updates: ['/gazebo',]
  tower_top_kinect/depth/camera_info: ['/gazebo',]
  head_camera_rgb/parameter_descriptions: ['/gazebo',]
  tf_static: ['/robot_state_publisher',]
  gazebo/parameter_descriptions: ['/gazebo',]
  head_camera_rgb/image_raw: ['/gazebo',]
  bottom_kinect/rgb/image_raw: ['/gazebo',]
  elektron/mobile_base_controller/odom: ['/gazebo',]
  tower/head_yaw_position_controller/command: ['/real_effector_tower_gazebo',]
  bottom_kinect/depth/points: ['/gazebo',]
  laser_scan: ['/gazebo',]
  elektron/mobile_base_controller/cmd_vel: ['/nodelet_manager',]
  tower/head_yaw_position_controller/pid/parameter_descriptions: ['/gazebo',]
  tower_top_kinect/parameter_descriptions: ['/gazebo',]
  bottom_kinect/rgb/camera_info: ['/gazebo',]
  rosout: ['/robot_state_publisher','/yocs_cmd_vel_mux','/nodelet_manager','/gazebo','/virtual_effector_base_controller','/real_effector_tower_gazebo','/virtual_effector_tower_controller','/virtual_receptor_cameras','/elektron/base_controller_spawner','/tower/tower_controller_spawner','/elektron/joint_state_controller','/mono_odometer','/visual_odom','/elektron_ids','/limits',]
  elektron_ids/info: ['/elektron_ids',]
  yocs_cmd_vel_mux/active: ['/nodelet_manager',]
  rosout_agg: ['/rosout',]
  bottom_kinect/parameter_descriptions: ['/gazebo',]
  elektron/joint_states: ['/gazebo',]
  tower/head_pitch_position_controller/command: ['/real_effector_tower_gazebo',]
  tower_top_kinect/parameter_updates: ['/gazebo',]
  tower/head_pitch_position_controller/pid/parameter_updates: ['/gazebo',]
  tower/head_yaw_position_controller/pid/parameter_updates: ['/gazebo',]
  head_camera_rgb/camera_info: ['/gazebo',]
  tower_top_kinect/rgb/image_raw: ['/gazebo',]
  gazebo/link_states: ['/gazebo',]
  visual_odom/info: ['/visual_odom',]
  mono_odometer/odometry: ['/mono_odometer',]
  gazebo/model_states: ['/gazebo',]
  clock: ['/gazebo',]
  bottom_kinect/depth/camera_info: ['/gazebo',]
  bottom_kinect/depth/image_raw: ['/gazebo',]
  mono_odometer/info: ['/mono_odometer',]
  yocs_cmd_vel_mux/parameter_descriptions: ['/nodelet_manager',]
  mono_odometer/pose: ['/mono_odometer',]
  limits/info: ['/limits',]
  gazebo/parameter_updates: ['/gazebo',]

subscribers:
  elektron/mobile_base_controller/cmd_vel: ['/gazebo',]
  gazebo/set_model_state: ['/gazebo',]
  gazebo/set_link_state: ['/gazebo',]
  mono_odometer/info: ['/visual_odom',]
  mux_vel_keyboard/cmd_vel: ['/nodelet_manager',]
  head_camera_rgb/camera_info: ['/mono_odometer',]
  tower_top_kinect/rgb/image_raw: ['/virtual_receptor_cameras',]
  nodelet_manager/bond: ['/nodelet_manager','/yocs_cmd_vel_mux',]
  rosout: ['/rosout',]
  tf: ['/mono_odometer',]
  mono_odometer/odometry: ['/visual_odom',]
  tf_static: ['/mono_odometer',]
  clock: ['/robot_state_publisher','/yocs_cmd_vel_mux','/nodelet_manager','/virtual_effector_base_controller','/gazebo','/real_effector_tower_gazebo','/virtual_effector_tower_controller','/virtual_receptor_cameras','/elektron/base_controller_spawner','/tower/tower_controller_spawner','/elektron/joint_state_controller','/visual_odom','/mono_odometer','/elektron_ids','/limits',]
  bottom_kinect/rgb/image_raw: ['/virtual_receptor_cameras',]
  mux_vel_nav/cmd_vel: ['/nodelet_manager',]
  head_camera_rgb/image_raw: ['/virtual_receptor_cameras','/mono_odometer',]
  elektron/joint_states: ['/robot_state_publisher',]
  tower/head_yaw_position_controller/command: ['/gazebo',]
  mux_vel_raw/cmd_vel: ['/nodelet_manager','/visual_odom','/limits',]
  tower/head_pitch_position_controller/command: ['/gazebo',]
  laser_scan: ['/limits',]
